CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA;
USE BD_APLICATIVO_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    QTD_MUSICA INTEGER NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    FAIXA_ETARIA INTEGER NOT NULL,
    AVALIACAO VARCHAR(255) NOT NULL,
    FK_CPF_ARTISTA VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER PRIMARY KEY,
    LETRA VARCHAR (255) NOT NULL,
    DURACAO DOUBLE NOT NULL,
    QTD_VISUALIZACAO INTEGER NOT NULL,
    FAIXA_ETARIA INTEGER NOT NULL,
    COMENTARIO VARCHAR (255),
    FK_ID_GENERO INTEGER,
	FK_ID_ALBUM INTEGER,
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID) ON DELETE CASCADE
);



    
    
	
