CREATE DATABASE IF NOT EXISTS BD_CONSULTAS_MEDICAS;
USE BD_CONSULTAS_MEDICAS;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM INTEGER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ESPECIALIZADO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LAUDO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER PRIMARY KEY,
    NUMERO INTEGER NOT NULL,
    HORARIO VARCHAR(50) NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    DATA DATE NOT NULL,
    FK_CRM_MEDICO INTEGER NOT NULL,
    FK_CPF_PACIENTE VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF) ON DELETE CASCADE
);