CREATE DATABASE IF NOT EXISTS BD_GERENCIADOR_PROJETOS;
USE BD_GERENCIADOR_PROJETOS;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER PRIMARY KEY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CARACTERISTICAS VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    ORCAMENTO DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    FUNCAO VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CARGA_HORARIA VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS POSSUIR(
	ID INTEGER PRIMARY KEY,
    FK_CPF_FUNCIONARIO VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER PRIMARY KEY,
    IDADE INTEGER NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    FK_ID_PROJETO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID) ON DELETE CASCADE
);
    