CREATE DATABASE IF NOT EXISTS BD_GERENCIAMENTO_BIBLIOTECA_ONLINE;
USE BD_GERENCIAMENTO_BIBLIOTECA_ONLINE;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    FOTO BLOB,
    BIOGRAFIA VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(255) NOT NULL,
    EDITORA VARCHAR (255) NOT NULL,
    CAPA BLOB NOT NULL,
    DESCRICAO VARCHAR(255),
    FK_CPF_AUTOR VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_CPF_AUTOR) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LEITOR(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_LEITOR(
	ID INTEGER PRIMARY KEY,
    FK_ID_LIVRO_DIGITAL INTEGER NOT NULL,
    FK_ID_LEITOR INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_LEITOR) REFERENCES LEITOR(ID) ON DELETE CASCADE
);
