CREATE DATABASE IF NOT EXISTS BD_GESTAO_SUPERMERCADO;
USE BD_GESTAO_SUPERMERCADO;

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR (30) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    VALOR DOUBLE NOT NULL,
    QTD_CLIENTES INTEGER NOT NULL,
    QTD_ESTOQUE INTEGER NOT NULL,
    AVALIACAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR (255) NOT NULL,
    QTD INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    QTD INTEGER NOT NULL,
    VALIDADE DATE NOT NULL,
    PRECO DOUBLE NOT NULL, 
    NOME VARCHAR(255) NOT NULL,
    FOTO BLOB,
    FK_ID_CATEGORIA INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FORNECE(
	ID INTEGER PRIMARY KEY,
    FK_CNPJ_FORNECEDOR VARCHAR (20) NOT NULL,
    FK_ID_PRODUTO INTEGER NOT NULL,
    FOREIGN KEY(FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE,
    FOREIGN KEY(FK_ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE
);