CREATE DATABASE IF NOT EXISTS BD_RES_HOTEL;
USE BD_RES_HOTEL;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    LOCALIZACAO VARCHAR(255) NOT NULL,
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF VARCHAR(14) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (15) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER PRIMARY KEY,
    NUMERO INTEGER NOT NULL,
    FOTO BLOB,
    FK_CNPJ_HOTEL VARCHAR(20) NOT NULL,
    FOREIGN KEY(FK_CNPJ_HOTEL) REFERENCES HOTEL(CNPJ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTO_HOSPEDE(
	ID INTEGER PRIMARY KEY,
    FK_ID_QUARTO INTEGER NOT NULL,
    FK_CPF_HOSPEDE VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_ID_QUARTO) REFERENCES QUARTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_HOSPEDE) REFERENCES HOSPEDE(CPF) ON DELETE CASCADE
);


