CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AEREAS;
USE BD_RESERVAS_AEREAS;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR (30) NOT NULL,
    NOME VARCHAR (255) NOT NULL,
    PASSAPORTE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOO(
	CODIGO INTEGER PRIMARY KEY,
    DATA DATE NOT NULL,
    VALOR DOUBLE NOT NULL, 
    DESCRICAO VARCHAR(255),
    ENDERECO VARCHAR(255) NOT NULL,
    COMPANHIA VARCHAR(255) NOT NULL,
    QTD_PASSAGEIROS INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER PRIMARY KEY,
    NUMERO INTEGER NOT NULL,
    DESCRICAO VARCHAR(255),
    CLASSE VARCHAR(255) NOT NULL,
    VALOR DOUBLE NOT NULL,
    FK_CPF_PASSAGEIRO VARCHAR(14) NOT NULL,
    FK_CODIGO_VOO INTEGER NOT NULL,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_CODIGO_VOO) REFERENCES VOO(CODIGO) ON DELETE CASCADE
);