CREATE DATABASE IF NOT EXISTS BD_STREAM_VIDEO;
USE BD_STREAM_VIDEO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER PRIMARY KEY,
    IDADE INTEGER NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TEMPO DOUBLE NOT NULL,
    FK_ID_CATEGORIA INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VISUALIZACAO(


	ID INTEGER PRIMARY KEY,
    INTERACAO VARCHAR(255),
    FK_ID_VIDEO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_VIDEO) REFERENCES VIDEO(ID) ON DELETE CASCADE
);