CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS;
USE BD_ALUGUEL_PRODUTOS;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);
CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY(FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY(FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
);

-- DML-LINGUAGEM DE MANIPULAÇÃO
-- INSERT - INSERIR
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("email@email.com","1999999999","1234556789","Isa");

INSERT INTO CLIENTE(EMAIL,TELEFONE,CPF,NOME)
VALUES("isabellafgarcia2@gmail.com","19974263169","48263444810","Isabella Garcia");

INSERT INTO CLIENTE(NOME,EMAIL,TELEFONE,CPF)
VALUES ("Gabriel","gabriel@email.com","19994154099","222222222222");

UPDATE CLIENTE
SET EMAIL = "isabellabobrinha@email.com"
WHERE CLIENTE_ID = 2;

UPDATE CLIENTE
SET EMAIL = "isabellajoaninha1702@email.com"
WHERE CLIENTE_ID = 3;

-- SELECT-SELECIONAR
SELECT * FROM CLIENTE;

-- INSERIR PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("MacBook M4","Notebook Apple",4789.90,5);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Smartphone Nova X12","Smartphone 5G com câmera tripla de 108MP e tela AMOLED 6.7",4300,12);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Notebook Quantum Pro 15","Notebook ultrafino com processador i7, 16GB RAM e SSD 1TB",6789.99,120);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Fone Bluetooth AirSound Max","Fones sem fio com cancelamento ativo de ruído e bateria de 30h",709,3700);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("Smartwatch Pulse Fit 3","Relógio inteligente com monitor cardíaco, GPS e resistência à água",1099,456);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("Monitor UltraView 4K 32 ","Monitor UHD 4K com taxa de atualização de 144Hz",2499,567);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("Mouse Gamer SpeedFire GX","Mouse RGB com 12 botões programáveis e sensor de 26.000 DPI",349,333);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Console GameBox One Z","Console de última geração com suporte a jogos em 8K",4999.99,541);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("Câmera ProShot Z7","Câmera profissional mirrorless 45MP com gravação em 8K",12499,79);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("Carregador Portátil TurboCharge 30.000mAh","Powerbank com carregamento rápido PD 65W, ideal para notebooks",799,43);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("Microfone StudioVoice Pro","Microfone condensador USB com captação de alta qualidade",1299,88);

INSERT INTO PRODUTO(NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("Roteador Wi-Fi 6X Turbo","Roteador Wi-Fi 6 com velocidade de até 10Gbps, suporte para múltiplos dispositivos e alcance ampliado",3689,99);

SELECT *FROM PRODUTO;

-- INSERRIR ALUGUEIS
SELECT *FROM CLIENTE;
SELECT *FROM PRODUTO;

-- ATUALIZAR UM REGISTRO (UPDATE)
UPDATE PRODUTO
SET	   PRECO = 3500
WHERE  PRODUTO_ID = 1;

UPDATE PRODUTO
SET	   PRECO = 7569
WHERE  PRODUTO_ID = 10;

UPDATE PRODUTO
SET	   PRECO = 2346
WHERE  PRODUTO_ID = 5;

UPDATE PRODUTO
SET	   PRECO = 8796
WHERE  PRODUTO_ID = 11;

UPDATE PRODUTO
SET	   QTD_DISPONIVEL = 28
WHERE  PRODUTO_ID = 9;

UPDATE PRODUTO
SET	   QTD_DISPONIVEL = 7
WHERE  PRODUTO_ID = 12;

UPDATE PRODUTO
SET	   QTD_DISPONIVEL = 01
WHERE  PRODUTO_ID = 2;

UPDATE PRODUTO 
SET QTD_DISPONIVEL = 77
WHERE PRODUTO_ID = 3;

UPDATE PRODUTO
SET	   QTD_DISPONIVEL = 129
WHERE  PRODUTO_ID = 7;

SELECT *FROM PRODUTO;

INSERT INTO ALUGUEL ( DATA_ALUGUEL,
					  DATA_DEVOLUCAO,
                      VALOR_TOTAL,
                      FK_CLIENTE_ID,
                      FK_PRODUTO_ID)
VALUES ("2025-09-24",
		"2025-10-01",
        7890,
        3,
        2);
        
INSERT INTO ALUGUEL ( DATA_ALUGUEL,
					  DATA_DEVOLUCAO,
                      VALOR_TOTAL,
                      FK_CLIENTE_ID,
                      FK_PRODUTO_ID)
VALUES("2025-09-08","2025-10-08", 4098, 1,5);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-24", "2025-10-01", 2500, 1, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-25", "2025-10-02", 3500, 2, 2);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-26", "2025-10-05", 780, 3, 3);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-27", "2025-10-03", 1100, 1, 4);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-28", "2025-10-06", 4999, 2, 5);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-29", "2025-10-07", 850, 3, 6);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-09-30", "2025-10-08", 1299, 1, 7);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-01", "2025-10-09", 3000, 2, 8);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-02", "2025-10-10", 550, 3, 9);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-03", "2025-10-11", 2100, 1, 10);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-04", "2025-10-12", 650, 2, 11);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-05", "2025-10-13", 1499, 3, 12);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-06", "2025-10-14", 3999, 1, 2);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-07", "2025-10-15", 780, 2, 4);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-08", "2025-10-16", 2200, 3, 6);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-09", "2025-10-17", 950, 1, 8);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-10", "2025-10-18", 2899, 2, 10);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-11", "2025-10-19", 1150, 3, 12);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-12", "2025-10-20", 700, 1, 3);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ("2025-10-13", "2025-10-21", 3200, 2, 7);

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-11-09"
WHERE ALUGUEL_ID = 13;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-11-15"
WHERE ALUGUEL_ID = 9;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-03"
WHERE ALUGUEL_ID = 7;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-11-09"
WHERE ALUGUEL_ID = 13;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-11-22"
WHERE ALUGUEL_ID = 19;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-09"
WHERE ALUGUEL_ID = 3;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-31"
WHERE ALUGUEL_ID = 20;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2025-12-23"
WHERE ALUGUEL_ID = 3;

SELECT *FROM ALUGUEL;

-- APAGAR UM REGISTRO (DELETE)
DELETE FROM CLIENTE WHERE CLIENTE_ID = 1;
SELECT *FROM CLIENTE;

DELETE FROM PRODUTO WHERE PRODUTO_ID = 4;
SELECT *FROM PRODUTO;

DELETE FROM ALUGUEL WHERE ALUGUEL_ID = 3;
SELECT *FROM ALUGUEL; 

SELECT * 
FROM CLIENTE
WHERE CLIENTE_ID = 2;

SELECT NOME,
	   PRECO
FROM PRODUTO
WHERE PRODUTO_ID = 3;




